### ISSUE TITLE
HTML-CSS Week2 Feedback

### ISSUE THREAD

**Issue by Swapna-Sahu** [somayehdvr/hyf-homework#1]
Good job in working on this website. Nicely made responsive website. Happy Coding :) 

For banner :
You have used this - background-position: right;
Instead try center it solved the problem.

Not sure why did u used this. I think it is not required and style for this section 
```
<li>
<ul>
<li><a>History</a></li>
</ul>
</li>
```
Here you missing ul after first li. You cannot have li inside another li.

**Comment by somayehdvr** [comment]
Hi,

Thank you for the review.
Have a nice day.
